version: '3.8'

services:
  app:
    build: .
    container_name: APP_GESTION_DOCUMENTAL
    ports:
      - "3110:3110"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/gestion_documental
      - EMAIL_SENDER=harvest.hero.app@gmail.com
      - EMAIL_PASSWORD=bhyu xsdt vmyl pejo
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - APP_BASE_URL=http://192.168.0.106:3110
      - RUN_DB_INIT=false
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: gestion_documental_db
    environment:
      - POSTGRES_DB=gestion_documental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
